---
- name: update status
  operator_sdk.util.k8s_status:
    api_version: "{{operator_api_version}}"
    kind: "{{operator_kind}}"
    name: "{{ansible_operator_meta.name}}"
    namespace: "{{ansible_operator_meta.namespace}}"
    conditions:
    - type: Running
      status: "True"
      reason: "{{reasontext}}"
      message: "{{messagetext}}"
