apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "aws.xyzcompany.com/v1",
          "kind": "AWSVMSchedulerStart",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "vm-scheduler-ansible-operator",
              "app.kubernetes.io/instance": "awsvmschedulerstart-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "awsvmschedulerstart",
              "app.kubernetes.io/part-of": "vm-scheduler-ansible-operator"
            },
            "name": "awsvmschedulerstart-sample"
          },
          "spec": {
            "awsSecretName": "aws-secret",
            "image": "quay.io/manoj_dhanorkar/awsvmscheduler:v1.0",
            "instanceIds": "i-00db611adab6f713d,i-0ef1d87bdf4dd3ad1",
            "startSchedule": "0 9 * * 1"
          }
        },
        {
          "apiVersion": "aws.xyzcompany.com/v1",
          "kind": "AWSVMSchedulerStop",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "vm-scheduler-ansible-operator",
              "app.kubernetes.io/instance": "awsvmschedulerstop-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "awsvmschedulerstop",
              "app.kubernetes.io/part-of": "vm-scheduler-ansible-operator"
            },
            "name": "awsvmschedulerstop-sample"
          },
          "spec": {
            "awsSecretName": "aws-secret",
            "image": "quay.io/manoj_dhanorkar/awsvmscheduler:v1.0",
            "instanceIds": "i-00db611adab6f713d,i-0ef1d87bdf4dd3ad1",
            "stopSchedule": "0 21 * * 5"
          }
        },
        {
          "apiVersion": "azure.xyzcompany.com/v1",
          "kind": "AZVMSchedulerStart",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "vm-scheduler-ansible-operator",
              "app.kubernetes.io/instance": "azvmschedulerstart-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "azvmschedulerstart",
              "app.kubernetes.io/part-of": "vm-scheduler-ansible-operator"
            },
            "name": "azvmschedulerstart-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "azure.xyzcompany.com/v1",
          "kind": "AZVMSchedulerStop",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "vm-scheduler-ansible-operator",
              "app.kubernetes.io/instance": "azvmschedulerstop-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "azvmschedulerstop",
              "app.kubernetes.io/part-of": "vm-scheduler-ansible-operator"
            },
            "name": "azvmschedulerstop-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "gcp.xyzcompany.com/v1",
          "kind": "GCPVMSchedulerStart",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "vm-scheduler-ansible-operator",
              "app.kubernetes.io/instance": "gcpvmschedulerstart-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "gcpvmschedulerstart",
              "app.kubernetes.io/part-of": "vm-scheduler-ansible-operator"
            },
            "name": "gcpvmschedulerstart-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "gcp.xyzcompany.com/v1",
          "kind": "GCPVMSchedulerStop",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "vm-scheduler-ansible-operator",
              "app.kubernetes.io/instance": "gcpvmschedulerstop-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "gcpvmschedulerstop",
              "app.kubernetes.io/part-of": "vm-scheduler-ansible-operator"
            },
            "name": "gcpvmschedulerstop-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2023-01-11T05:51:47Z"
    operators.operatorframework.io/builder: operator-sdk-v1.26.0
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
  name: vm-scheduler-ansible-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: AWSVMSchedulerStart
      name: awsvmschedulerstarts.aws.xyzcompany.com
      version: v1
    - kind: AWSVMSchedulerStop
      name: awsvmschedulerstops.aws.xyzcompany.com
      version: v1
    - kind: AZVMSchedulerStart
      name: azvmschedulerstarts.azure.xyzcompany.com
      version: v1
    - kind: AZVMSchedulerStop
      name: azvmschedulerstops.azure.xyzcompany.com
      version: v1
    - kind: GCPVMSchedulerStart
      name: gcpvmschedulerstarts.gcp.xyzcompany.com
      version: v1
    - kind: GCPVMSchedulerStop
      name: gcpvmschedulerstops.gcp.xyzcompany.com
      version: v1
  description: Ansible based operator to schedule start/stop of compute instances
  displayName: vm-scheduler-ansible-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          - pods
          - pods/exec
          - pods/log
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - batch
          resources:
          - cronjobs
          - jobs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - aws.xyzcompany.com
          resources:
          - awsvmschedulerstarts
          - awsvmschedulerstarts/status
          - awsvmschedulerstarts/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - aws.xyzcompany.com
          resources:
          - awsvmschedulerstops
          - awsvmschedulerstops/status
          - awsvmschedulerstops/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - azure.xyzcompany.com
          resources:
          - azvmschedulerstops
          - azvmschedulerstops/status
          - azvmschedulerstops/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - azure.xyzcompany.com
          resources:
          - azvmschedulerstarts
          - azvmschedulerstarts/status
          - azvmschedulerstarts/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - gcp.xyzcompany.com
          resources:
          - gcpvmschedulerstarts
          - gcpvmschedulerstarts/status
          - gcpvmschedulerstarts/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - gcp.xyzcompany.com
          resources:
          - gcpvmschedulerstops
          - gcpvmschedulerstops/status
          - gcpvmschedulerstops/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: vm-scheduler-ansible-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: vm-scheduler-ansible-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: vm-scheduler-ansible-operator
          control-plane: controller-manager
        name: vm-scheduler-ansible-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:6789
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                - --leader-election-id=vm-scheduler-ansible-operator
                env:
                - name: ANSIBLE_GATHERING
                  value: explicit
                image: quay.io/gunjangarge/vm-scheduler-ansible-operator:v0.0.1
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 6789
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 6789
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 768Mi
                  requests:
                    cpu: 10m
                    memory: 256Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: vm-scheduler-ansible-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: vm-scheduler-ansible-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ansible
  - aws
  - az
  - gcp
  - compute
  - schedule
  links:
  - name: Vm Scheduler Ansible Operator
    url: https://vm-scheduler-ansible-operator.domain
  maintainers:
  - email: gunjangarge@gmail.com
    name: Gunjan Garge
  maturity: alpha
  provider:
    name: Gunjan Garge
    url: https://github.com/gunjangarge/vm-scheduler-ansible-operator
  version: 0.0.1
