# permissions for end users to view azvmschedulerstarts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: azvmschedulerstart-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vm-scheduler-ansible-operator
    app.kubernetes.io/part-of: vm-scheduler-ansible-operator
    app.kubernetes.io/managed-by: kustomize
  name: azvmschedulerstart-viewer-role
rules:
- apiGroups:
  - azure.xyzcompany.com
  resources:
  - azvmschedulerstarts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - azure.xyzcompany.com
  resources:
  - azvmschedulerstarts/status
  verbs:
  - get
