# permissions for end users to view gcpvmschedulerstops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gcpvmschedulerstop-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vm-scheduler-ansible-operator
    app.kubernetes.io/part-of: vm-scheduler-ansible-operator
    app.kubernetes.io/managed-by: kustomize
  name: gcpvmschedulerstop-viewer-role
rules:
- apiGroups:
  - gcp.xyzcompany.com
  resources:
  - gcpvmschedulerstops
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gcp.xyzcompany.com
  resources:
  - gcpvmschedulerstops/status
  verbs:
  - get
