apiVersion: aws.xyzcompany.com/v1
kind: AWSVMSchedulerStart
metadata:
  labels:
    app.kubernetes.io/name: awsvmschedulerstart
    app.kubernetes.io/instance: awsvmschedulerstart-sample
    app.kubernetes.io/part-of: vm-scheduler-ansible-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: vm-scheduler-ansible-operator
  name: awsvmschedulerstart-sample
spec:
  # TODO(user): Add fields here
  image: "quay.io/manoj_dhanorkar/awsvmscheduler:v1.0"
  
  # Provide comma separated list of AWS instance ids which will be scheduled by CR 
  instanceIds: "i-00db611adab6f713d,i-0ef1d87bdf4dd3ad1"

  # Schedule period for the CronJob.
  # This spec allow you to setup the start schedule for VM
  # Default: "0 9 * * *" # every weekday at 9 AM
  startSchedule: "0 9 * * 1"
  awsSecretName: "aws-secret"
